services:
  - type: web
    name: InsiderInsight
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: insider-insight-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: insider-insight-db
    plan: starter
    user: insider-insight-db
