services:
  - type: web
    name: InsiderInsight
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: insider-insight-db
    # Additional configuration for your web service...

databases:
  - name: insider-insight-db
    plan: starter
    engine: postgres
    version: "12" # Specify the version you need; check Render's documentation for supported versions.
