services:
  - type: web
    name: InsiderInsight
    env: ruby
    plan: free
    buildCommand: "bundle install && rails assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: insider-insight-db
          property: connectionString
    # Additional configuration for your web service...

databases:
  - name: insider-insight-db
    plan: starter

