services:
  - type: web
    name: InsiderInsight
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: insider-insight-db
          property: connectionString
    # Additional configuration for your web service...

databases:
  - name: insider-insight-db
    plan: starter

